version: "3.9"

services:
  spike-message-board-mysql:
    image: mysql:8
    container_name: spike-message-board-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app
      MYSQL_USER: appuser
      MYSQL_PASSWORD: app_pass
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always

  spike-message-board-backend:
    build:
      context: ./experiment--express-with-nextjs
      dockerfile: Dockerfile
    container_name: spike-message-board-backend
    depends_on:
      - spike-message-board-mysql
    expose:
      - "3001"
    environment:
      PORT: 3001
      DATABASE_URL: "mysql://appuser:app_pass@spike-message-board-mysql:3306/app"
    restart: always

  spike-message-board-nginx:
    image: nginx:latest
    container_name: spike-message-board-nginx
    depends_on:
      - spike-message-board-backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - certbot-www:/var/www/certbot
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    restart: always

volumes:
  mysql-data: {}
  certbot-etc: {}
  certbot-var: {}
  certbot-www: {}