version: "3.9"

services:
  spike-message-board-backend:
    build:
      context: ../../experiment--express-with-nextjs
      dockerfile: Dockerfile
      args:
        DATABASE_URL: ${DATABASE_URL}
    env_file:
      - ./.env
    environment:
      PORT: ${PORT}
      DATABASE_URL: ${DATABASE_URL}

  spike-message-board-nginx:
    image: nginx:latest
    depends_on:
      - spike-message-board-backend
    ports:
      - "80:80"
    volumes:
      - ../nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro
