version: "3.9"

services:
  spike-message-board-mysql:
    image: mysql:8
    container_name: spike-message-board-mysql
    env_file:
      - ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql

  spike-message-board-backend:
    build:
      context: ../../experiment--express-with-nextjs
      dockerfile: Dockerfile
      args:
        DATABASE_URL: ${DATABASE_URL}
    container_name: spike-message-board-backend
    depends_on:
      - spike-message-board-mysql
    env_file:
      - ./.env
    environment:
      PORT: ${PORT}
      DATABASE_URL: ${DATABASE_URL}
    expose:
      - "3001"

  spike-message-board-nginx:
    image: nginx:latest
    container_name: spike-message-board-nginx
    depends_on:
      - spike-message-board-backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - certbot-www:/var/www/certbot
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt

volumes:
  mysql-data: {}
  certbot-etc: {}
  certbot-var: {}
  certbot-www: {}
