version: "3.9"

services:
  spike-message-board-backend:
    build:
      context: ../../experiment--express-with-nextjs
      dockerfile: Dockerfile
      args:
        DATABASE_URL: ${DATABASE_URL}
    container_name: spike-message-board-backend
    restart: always
    env_file:
      - ./.env
    environment:
      PORT: ${PORT}
      DATABASE_URL: ${DATABASE_URL}
    expose:
      - "3001"
    volumes:
      - sqlite-data:/app/data

  spike-message-board-nginx:
    image: nginx:latest
    container_name: spike-message-board-nginx
    restart: always
    depends_on:
      - spike-message-board-backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - certbot-www:/var/www/certbot
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt

volumes:
  sqlite-data: {}
  certbot-etc: {}
  certbot-var: {}
  certbot-www: {}
